language: java
jdk: oraclejdk8
script: ant dist
deploy:
  provider: releases
  api_key:
    secure: dGdWIXB3X7S+c5wewASVQ/K5QtJs8G8CwNduECFUmxWAuFwMGvG+7qY2OIjIT/Azd5MN91vYsj4jkS7tct/Qe/R+RPk2PjYOv5WBQUi9XZtyT+cwLbeE/VdVJ88JkAJxZSuQ9vfrl2pzfk6beOGqDhWZbtR1sl3dmWZqh39BRua5o8JmXqCUgDvPKaavnqDm/1KOF2QMZnO9BiMiIjf1zkdMpf1Nuxlpjl1L6hiCWYhY87j8e7gTnQMPiH8H0X9JmDFP5irSj+vcn9YrB15oZRhNCcmXz4H2fLtbVzWKhcQecJfeo2i7kNM4hfPg52/Aq9eGoNKA6wbGKA07/Fau08zYstDw+rQIO/CVKITNFmvCVf+d7ITY5zcS7nQbeED2dVGkLpoW7xukwyohviIqVH9vFP1qS/M54Lt0KDhlnIe5qIktN62D1mSV7ekBes9ZwsYoPN9QycEv988RZbz1BrKMhzgx9I7E3MHwHOBxiroeYsAstJbXWb1tjfMqY2Ic6BfJ6PhD3G6W1QW/77LZJj9n/TtGm5BidSWB/mWrntu7ViT6ILdWAXfyjNGsYP+NYw7yOw7561oQE2NnF3YfXM57KxRtnHC6aVd4Q4BSmcLY7ek0GJ7nEuxR8FHU9eg732JRAGgMcQD6keDis5nGof/ZlIBjqdusMzr4QRkjczk=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  draft: true
  on:
    tags: true
    all_branches: true