language: java
jdk: oraclejdk8
script: ant dist
deploy:
  provider: releases
  api_key:
    secure: MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA5wkE0S4Sv795tg4qJsl7\nR2FwitlGldzj2svatqp1q49Igg6GXTshy7BTSwQ0Kqj+FMKvLQO/Nchnavn6QH+l\nGBucpjtguaOcdhYJMLOxVt8rMy8f4onhJfGvH4JMtv4SKO/lvSHka0XBQ54V+OcN\nyN4UYU5pggpKt8Yo45c8ITP/rWdd+Q2JPX63OP5HqUeo4aYobJ/v2iH7J+kFtTnd\nuMDEdhJLSDKqNMHOpKJqoVSy80nRPgZJXkKLIXBkArSV1ZgYu9eR75x9J4skRW5D\n4S9+UzyzhfFlARDCK+ZCqhd9zXJxsm62R+WzWMcOQ/FByNIcWEpjuxejzTOR3f4a\nT3dmnIw2BcHRALD2ep0U/Qd/rgQOSzT747Rg5Sy7u+mJh9GL/vYIhKat0vXChycY\n/0H7VZus5fA2HMVAHroaIq7b8iXRHAkeGeI/gJGnpH4Za2FdLf7Hy5LQSB8aU/DM\ndLSNCOBgrFxb3QV3j2O4ct/PnnihfVW+XU/wiiIz0OL9I+MLHoR0LNXm/xZm0M2b\n/UYQX8qNo1jLzYVem4Cmkw6g+Oy7gZ+Tzaoxx069xzWcIMCZLxQJrRfzjBbp4M6L\n7OfHWiakNavCYSerasPtu5oUOohFUXoOpHncV3eZrfcr0Bh5SbSaGov3t4Wawk6Y\nrViJsYAYLd+0o2jRBy0plhkCAwEAAQ==
  file_glob: true
  file: dist/*
  skip_cleanup: true
  draft: true
  on:
    tags: true
    all_branches: true