language: java
jdk: oraclejdk8
script: ant dist
deploy:
  provider: releases
  api_key:
    secure: VdGBPB7BKdT3ornYwRgI8QYfu6+jNbd/5M49+RnGzEp91/cB7r1H9Spt2EWN5HAbaRR4rLPfMpbX7uiW+6Jnt6cMcBIL1c+MUIJaJ7yGr5yq1F4TlsIrxlIYz2JZ9c6kvrrzG7mPzVf0orSpPWijuz/QsU3ASz/B5MgDfq2LbQyzbZjTO0EQu+aTrd/ouOrZ26QY0dqXF2KPoUBcnLQ8r7tniD3rAKr8yVmDyZtmGUusDvh81OMVqaFuUP/s8eytAjz5hFQWXi4smvLBxMq/GlSJ/8lnr1y5J+EhUVGq42bnaDtXRBKiXnDEvb5Cl34LXEzKCnfT+HfNK67GtZBqUgmNWW/wQTVE2BZSZBW0I6I+KYGZnAPJyf3CVpgQKvoUKA2TwikRx0Ht1cnBijU4RLJrBhzj00myGzWY9+g65YW7UCsNYuYvuXVEWeLxAW0HFVocOqFe2LSUIzd4su71JHlbsqot+7FpPTTsbishlPWvL6S5mzE28DooGeeZRqyb9XWOvfvX8hBCGPDKPE4AFJmO5nZulZKFAg2gJiAiOPpZDB0XMd0OodBVb2sNc/dKKrZt5vua45bGG7u0nQipsqioGeRzSjAvFbYGLMDlrdaM7kQmnEDBVVPh1PpD6jqrAPl45I6E+9G60ay3N3zqQO/cddONf+S3dezMdX/sN9k=
  file: dist/*
  draft: true
  on:
    tags: true
    all_branches: true
